#! /bin/sh

# Disable bell
xset -b

# Set touchpad speed and tap to click (use xfce settings instead if available)
# xinput --list-props 'ETPS/2 Elantech Touchpad' &> /dev/null
# if [ $? -eq 0 ]; then
#   xinput --set-prop 'ETPS/2 Elantech Touchpad' 'libinput Accel Speed' 0.6
#   xinput --set-prop 'ETPS/2 Elantech Touchpad' 'libinput Tapping Enabled' 1
# fi

# swap left and right button (use xfce settings instead if available)
# KENSINGTON_TRACKBALL=$(xinput list | grep "Kensington Expert" | head -n 1 | sed -r 's/.*id=([0-9]+).*/\1/')
# if [ ! -z "$KENSINGTON_TRACKBALL" ]; then
#   xinput --set-button-map ${KENSINGTON_TRACKBALL} 3 2 1
# fi

# Keyboard rate (use xfce settings instead if available)
# xset r rate 300 50
