#! /bin/bash

# Disable bell
xset -b

# Set touchpad speed and tap to click if on my laptop
xinput --list-props 'ETPS/2 Elantech Touchpad' &> /dev/null
if [ $? -eq 0 ]; then
  xinput --set-prop 'ETPS/2 Elantech Touchpad' 'libinput Accel Speed' 0.6
  xinput --set-prop 'ETPS/2 Elantech Touchpad' 'libinput Tapping Enabled' 1
fi

# Keyboard rate
xset r rate 300 50
