#! /bin/bash

set -e

echo Commands are:
echo   check
echo   update-arch, update-aur, update-npm
echo   clean
echo

[[ $EUID = 0 ]] && >&2 echo "Do not run as root" && exit 1

if [ "$1" = "check" ]; then
  # Show systemd services that have entered in a failed state
  systemctl --failed
  # Show broken symlinks
  find -xtype l -print
  echo "Check complete"
  exit 0
fi

if [ "$1" = "update-arch" ]; then
  sudo pacman -Syu
  echo "Arch update complete"
  exit 0
fi

if [ "$1" = "update-aur" ]; then
  yay -Syu
  echo "AUR update complete"
  exit 0
fi

if [ "$1" = "update-npm" ]; then
  npm update -g
  echo "npm update complete"
  exit 0
fi

if [ "$1" = "clean" ]; then
  set +e
  # Remove orphans
  sudo pacman -Rns $(pacman -Qtdq)
  # Clean package cache
  sudo paccache -ruk0
  # Delete all cached except latest 3
  sudo paccache -r
  # Discard blocks not in use by the filesystem
  sudo fstrim -av
  if [ $(./ask_yes_or_no "Prune docker?") == "yes" ]; then
    docker system prune
  fi
  if [ $(./ask_yes_or_no "Empty trash?") == "yes" ]; then
    ./empty_trash
  fi
  if [ $(./ask_yes_or_no "Clear thumbnail cache?") == "yes" ]; then
    ./clear_thumbnail_cache
  fi
  if [ $(./ask_yes_or_no "Clear shell history?") == "yes" ]; then
    ./clear_shell_history
  fi
  echo "Clean complete"
  set -e
  exit 0
fi

exit 1
