#! /bin/bash

set -e

if [ -z "$1" ]; then
  >&2 echo "Argument must be provided" && exit 1
fi

hex=$1
if [[ $hex == "#"* ]]; then
  hex=$(echo $1 | awk '{print substr($0,2)}')
fi
r=$(printf '0x%0.2s' "$hex")
g=$(printf '0x%0.2s' ${hex#??})
b=$(printf '0x%0.2s' ${hex#????})
echo -e `printf "%03d" "$(((r<75?0:(r-35)/40)*6*6+(g<75?0:(g-35)/40)*6+(b<75?0:(b-35)/40)+16))"`
