#! /bin/bash

name="$1"
max_wait_term_s="${2}"

if [ -z "$name" ]; then
  >&2 echo "Provide process name"
  exit 1
fi

if pgrep -x "$name" > /dev/null; then
  killall -q "$name"
  waited=0
  while pgrep -u $UID -x "$name" >/dev/null; do
    sleep 1
    waited=`expr "$waited" + 1`
    if [ ! -z "$max_wait_term_s" ]; then
      if [ "$waited" -ge "$max_wait_term_s" ]; then
        try_kill=1
        break
      fi
    fi
  done
  if [ ! -z "$try_kill" ]; then
    killall -q -s SIGKILL "$name"
    sleep 2
  fi
  if pgrep -x "$name" > /dev/null; then
    >&2 echo "Failed to kill ${name}"
    exit 1
  fi
fi

exit 0
