#! /bin/bash

set -e

[[ $EUID = 0 ]] && >&2 echo "Do not run as root" && exit 1

use_mountpoint="${2:-$HOME/Android}"
echo "Using $use_mountpoint as mountpoint"
if [ -z "$use_mountpoint" ]; then
  >&2 echo "Mountpoint missing" && exit 1
fi
mkdir -p "$use_mountpoint"

if [ "$1" = "mount" ]; then
  if mountpoint -q "$use_mountpoint"; then
    >&2 echo "$use_mountpoint already in use" && exit 1
  fi
  if [ -z "$3" ]; then
    echo "Mounting default device"
    jmtpfs "$use_mountpoint"
  else
    echo "Mounting $3"
    # Expects <busnum>,<devnum>
    jmtpfs -device=$3 "$use_mountpoint"
  fi
elif [ "$1" = "umount" ]; then
  if mountpoint -q "$use_mountpoint"; then
    fusermount -u "$use_mountpoint"
  else
    >&2 echo "$use_mountpoint not mounted" && exit 1
  fi
else
  jmtpfs -l
  >&2 echo "Expects mount or umount argument" && exit 1
fi

echo "Finished"
exit 0
